### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Turbo-Tuning** [bri3d/a2l2xdf#4]
I get a similar error message with all a2l files I have tested. What am I doing wrong?
```
$ python3 a2l2xdf.py sa.a2l a2l2xdf.csv
Traceback (most recent call last):
  File "a2l2xdf.py", line 15, in <module>
    db.open_existing(argv[1]) if path.exists(f"{argv[1]}db") else db.import_a2l(argv[1])
  File "/home/chris/.local/lib/python3.7/site-packages/pya2l/__init__.py", line 115, in import_a2l
    prepro_result = prepro.process(self._a2lfn, encoding = detect_encoding(self._a2lfn))
  File "/home/chris/.local/lib/python3.7/site-packages/pya2l/preprocessor.py", line 160, in process
    data = self._process_file(file_name, join_lines = True, encoding = encoding)
  File "/home/chris/.local/lib/python3.7/site-packages/pya2l/preprocessor.py", line 173, in _process_file
    for num, line in enumerate(f_obj, 1):
  File "/usr/lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7497: ordinal not in range(128)
```

**Comment by bri3d** [comment]
This is a bug in the upstream pya2l library which I need to file and try to
have resolved. Replacing all non ASCII characters with ASCII in the A2L
using a text editor will help for now. Next you’ll probably have issues
with another pya2l bug involving name fields and //=, recommend replacing
all instances of //= with blanks. And then you’ll probably be able to get
an a2ldb generated.

**Comment by TheFlashBold** [comment]
Any names with `//` inside and empty names `""` are causing errors.
Fix non-ASCII errors ` LC_ALL=C tr -cd '\11\12\15\40-\176' < original.a2l > original-ascii.a2l`.
Then go through line by line fixing names or wrong formatting.
